apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: cloud-native-demo
  name: cloud-native-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cloud-native-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: cloud-native-demo
    spec:
      containers:
      - image: cloud-native-demo:1
        imagePullPolicy: IfNotPresent
        name: cloud-native-demo
        resources: {}
        env:
          - name: REDIS_HOST
            value: redis
          - name: REDIS_PORT
            value: "6379"
        command:
          - sh
          - -c
          - |
            python app.py --redis-host $(REDIS_HOST)
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 5
